name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/careervilla-backend:latest --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 400 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/careervilla-backend:latest
            docker stop careervilla-backend || true
            docker rm careervilla-backend || true
            docker run -d --name careervilla-backend -p 3000:3000 \
            -e CORS_URL=${{ vars.CORS_URL }} \
            -e db_URI=${{ vars.db_URI }} \
            -e JWT_SECRET=${{ vars.JWT_SECRET }} \
            -e STRIPE_SECRET_KEY=${{ vars.STRIPE_SECRET_KEY }} \
            ${{ secrets.DOCKER_USERNAME }}/careervilla-backend:latest
          EOF
